name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
          node-version: 18

      - name: CI
        run: |
          cd my-plugin
          npm ci
          npm run build
          cd ..
          npm ci

      - name: Create Docs
        run: |
          npm run docs

      - name: Run Tests
        run: |
          export FORBIDDEN_PHRASE=${{ github.repository }}
          echo The secret is:$FORBIDDEN_PHRASE

          export REQUIRED_PHRASE=API Reference
          echo The secret is:$REQUIRED_PHRASE

          npm run test
        env:
          REQUIRED_PHRASE: "API Reference,API%20Reference"
          FORBIDDEN_PHRASE: "# ${{ github.repository }},[${{ github.repository }}]"

