name: Publish to Wiki

on:
  push:
    branches:
      - main

concurrency:
  group: wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  wiki:
    name: Publish to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          path: ${{github.repository}}

      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: ${{github.repository}}.wiki

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build Docs
        run: |
          cd $GITHUB_WORKSPACE/${{github.repository}}
          npm ci
          npm run docs
          npm run format-docs

      - name: Push to Wiki
        run: |
          set -e
          find "$GITHUB_WORKSPACE/${{github.repository}}.wiki" -name "*.md" -delete
          cd $GITHUB_WORKSPACE/${{github.repository}}.wiki
          cp -r $GITHUB_WORKSPACE/${{github.repository}}/docs/* .
          cp -r $GITHUB_WORKSPACE/${{github.repository}}/wiki/* .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "update wiki" && git push
